
import { Fish, Rarity, Item, ItemCategory, ItemType } from './types';

export const PRESET_TAGS = ["萬聖節", "聖誕節", "泳池狂歡", "寶可夢"];
export const PRESET_CONDITIONS = ["白天", "晚上", "晨曦", "黃昏", "時空歪曲", "雨天", "大雨", "大日照"];

export const INITIAL_FISH: Fish[] = [
  {
    id: '001',
    name: '大眼草魚',
    description: '有著不成比例大眼睛的淡水魚，常在水草間發呆。',
    rarity: Rarity.OneStar,
    depthMin: 1,
    depthMax: 3,
    conditions: ['全天', '晴天', '陰天'],
    battleRequirements: '點擊頻率：低',
    specialNote: '',
    tags: ['新手區', '淡水'],
    variants: {
      normalMale: 'https://picsum.photos/seed/001-nm/400/300',
    }
  },
  {
    id: '002',
    name: '泥沼鯰',
    description: '身體滑溜溜的，喜歡躲在淤泥裡，拉力比想像中大。',
    rarity: Rarity.OneStar,
    depthMin: 5,
    depthMax: 8,
    conditions: ['晚上', '雨天'],
    battleRequirements: '維持張力在黃色區域',
    specialNote: '需使用重型鉛錘',
    tags: ['沼澤', '夜行性'],
    variants: {
      normalMale: 'https://picsum.photos/seed/002-nm/400/300',
    }
  },
  {
    id: '010',
    name: '翠玉鱸魚',
    description: '鱗片像寶石一樣閃爍著綠光的鱸魚，肉質鮮美。',
    rarity: Rarity.TwoStar,
    depthMin: 10,
    depthMax: 15,
    conditions: ['晨曦', '晴天'],
    battleRequirements: '需要快速反應QTE',
    specialNote: '',
    tags: ['溪流', '寶石系列'],
    variants: {
      normalMale: 'https://picsum.photos/seed/010-nm/400/300',
    }
  },
  {
    id: '015',
    name: '雷紋鰻',
    description: '背部有黃色閃電花紋，生氣時會放出微弱電流。',
    rarity: Rarity.TwoStar,
    depthMin: 20,
    depthMax: 50,
    conditions: ['雷雨', '大雨'],
    battleRequirements: '避免在牠放電(紅光)時拉線',
    specialNote: '絕緣手套必備',
    tags: ['雷屬性', '危險生物'],
    variants: {
      normalMale: 'https://picsum.photos/seed/015-nm/400/300',
    }
  },
  {
    id: '030',
    name: '深淵燈籠魚',
    description: '生活在極深水域，頭上的燈籠會迷惑釣客。',
    rarity: Rarity.ThreeStar,
    depthMin: 100,
    depthMax: 500,
    conditions: ['晚上', '霧天'],
    battleRequirements: '張力條會忽快忽慢，需要極高專注',
    specialNote: '需要螢光魚餌',
    tags: ['深海', '發光生物'],
    variants: {
      normalMale: 'https://picsum.photos/seed/030-nm/400/300',
    }
  },
  {
    id: '035',
    name: '赤炎鬥魚',
    description: '全身燃燒著像是火焰的靈氣，水溫會因為牠而升高。',
    rarity: Rarity.ThreeStar,
    depthMin: 800,
    depthMax: 1000,
    conditions: ['白天', '大日照'],
    battleRequirements: '連續點擊破壞護盾',
    specialNote: '使用黑曜石釣竿',
    tags: ['火屬性', '火山'],
    variants: {
      normalMale: 'https://picsum.photos/seed/035-nm/400/300',
    }
  },
  {
    id: '050',
    name: '月光女神',
    description: '傳說中映照著月亮的幻之魚，鰭如絲綢般飄逸。',
    rarity: Rarity.FourStar,
    depthMin: 0,
    depthMax: 5,
    conditions: ['晚上', '滿月'],
    battleRequirements: '完美判定連擊 x10',
    specialNote: '只吃月光花瓣',
    tags: ['傳說', '夢幻'],
    variants: {
      normalMale: 'https://picsum.photos/seed/050-nm/400/300',
    }
  },
  {
    id: '051',
    name: '遠古利維坦幼體',
    description: '雖然只是幼體，但已有吞噬小船的怪力，來自遠古的霸主。',
    rarity: Rarity.FourStar,
    depthMin: 3000,
    conditions: ['暴風雨', '時空歪曲'],
    battleRequirements: '需裝備鈦合金釣竿，耐力戰 5 分鐘',
    specialNote: '多人協作限定',
    tags: ['傳說', '巨獸', '深海'],
    variants: {
      normalMale: 'https://picsum.photos/seed/051-nm/400/300',
    }
  },
  {
    id: '999',
    name: '錯誤代碼：404',
    description: '一隻由雜訊構成的魚，存在於現實與數據的夾縫中。',
    rarity: Rarity.Special,
    depthMin: 0,
    conditions: ['時空歪曲', '電磁風暴'],
    specialNote: '不要盯著牠看太久',
    tags: ['異變', '數位'],
    variants: {
      normalMale: 'https://picsum.photos/seed/999-nm/400/300',
    }
  },
];

export const INITIAL_ITEMS: Item[] = [
  // --- Ball Maker Category (球匠類) ---
  {
    id: 'bm_001',
    name: '球果果',
    description: '外殼可當成膠囊狀容器使用，被用來製作各種精靈球的樹果。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.BallMaker,
  },
  {
    id: 'bm_002',
    name: '玉石',
    description: '不可思議的圓形石頭。與球果組合後，能夠激發出精靈球的性能。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.BallMaker,
  },
  {
    id: 'bm_003',
    name: '黑玉石',
    description: '不可思議的黑色石頭。與球果組合後，能夠激發出精靈球的性能。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.BallMaker,
  },
  {
    id: 'bm_004',
    name: '天藍玉石',
    description: '不可思議的天藍色石頭。與球果組合後，能夠激發出精靈球的性能。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.BallMaker,
  },
  {
    id: 'bm_005',
    name: '隕石碎片',
    description: '來自宇宙的隕石掉落的碎片之一。不可思議的是，含有與各種玉石一樣的成份。',
    source: '釣魚（水深＞５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.BallMaker,
  },
  {
    id: 'bm_006',
    name: '碎鐵',
    description: '天然的金屬片。可加工成鎖扣等零件，在製作各種精靈球時使用。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.BallMaker,
  },
  {
    id: 'bm_007',
    name: '複合金屬',
    description: '在大自然中含量極其稀少的特殊金屬。可加工成更為複雜且堅固的零件，在製作各種精靈球時使用。',
    source: '夥伴大冒險、釣魚（水深＞５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.BallMaker,
  },
  {
    id: 'bm_008',
    name: '紅色碎片',
    description: '紅色的小碎片。好像是以前製作的某道具的一部分。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.BallMaker,
  },
  {
    id: 'bm_009',
    name: '藍色碎片',
    description: '藍色的小碎片。好像是以前製作的某道具的一部分。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.BallMaker,
  },
  {
    id: 'bm_010',
    name: '綠色碎片',
    description: '綠色的小碎片。好像是以前製作的某道具的一部分。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.BallMaker,
  },
  {
    id: 'bm_011',
    name: '黃色碎片',
    description: '黃色的小碎片。好像是以前製作的某道具的一部分。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.BallMaker,
  },
  {
    id: 'bm_012',
    name: '結晶碎片',
    description: '沉在晶光池裡，閃耀著光輝的結晶碎片。好像是以前製作的某道具的一部分。',
    source: '夥伴大冒險、釣魚（水深＞５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.BallMaker,
  },
  {
    id: 'bm_013',
    name: '上鎖的膠囊*',
    description: '需用特殊鑰匙才能打開的堅固的容器，能夠用來製作某些膠囊類的道具',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.BallMaker,
  },

  // --- Ingredient Category (食材類) ---
  {
    id: 'ing_001',
    name: '誘糰原料',
    description: '與寶可夢的食物混合後，香氣會更加濃郁的口糧。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_002',
    name: '淺灘海鹽',
    description: '在名為淺灘洞穴的地方找到的海鹽，在某些岩石類寶可夢身上也能找到，可作為某些食物的食材。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_003',
    name: '香料組合',
    description: '製作露營料理時使用的食材之一。裡面有超過５０種的香料，很辣。',
    source: '？？？',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_004',
    name: '利木果',
    description: '具有天然的酸味的果實，可作為某些食物的食材',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_005',
    name: '桃桃果',
    description: '具有天然的甜味的果實，可作為某些食物的食材',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_006',
    name: '零餘果',
    description: '具有天然的澀味的果實，可作為某些食物的食材',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_007',
    name: '櫻子果',
    description: '具有天然的辣味的果實，可作為某些食物的食材',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_008',
    name: '莓莓果',
    description: '具有天然的苦味的果實，可作為某些食物的食材',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_009',
    name: '茸丹果',
    description: '具有天然的鹹味的果實，可作為某些食物的食材',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_010',
    name: '葡萄果',
    description: '具有天然的鮮味的果實，可作為某些食物的食材',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_011',
    name: '謎芝果',
    description: '來歷不明的珍貴樹果。不吃吃看，不會知道是什麼樣的味道。',
    source: '釣魚（水深＞５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_012',
    name: '哞哞鮮奶',
    description: '營養百分百，可作為某些食物的食材。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_013',
    name: '旺旺穀',
    description: '美麗且生氣勃勃的穀物，能用來製作陸地上的寶可夢喜愛的食物。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_014',
    name: '晶晶蜜',
    description: '閃耀著琥珀色光澤的蜜，能用來製作蟲寶可夢和妖精類寶可夢喜愛的食物。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_015',
    name: '滾滾豆',
    description: '結實飽滿的大顆豆子，能用來製作鳥寶可夢和魚寶可夢喜愛的食物。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_016',
    name: '糯糯菇',
    description: '碩大而成熟的蕈菇，能用來製作怪獸類和龍類寶可夢喜愛的食物。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_017',
    name: '堅堅礦',
    description: '晶瑩通透的礦物，能用來製作草類和岩石類寶可夢喜愛的食物。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_018',
    name: '起司片',
    description: '帶有鹹味的食材。切成薄片的起司。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_019',
    name: '飽伯罐頭',
    description: '製作露營料理時使用的食材之一。飽伯賣的罐頭不知為何在伽勒爾很受歡迎。',
    source: '夥伴大冒險、釣魚（水深＞５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_020',
    name: '巴哈罐頭',
    description: '製作露營料理時使用的食材之一。巴哈賣的罐頭不知為何在伽勒爾很受歡迎',
    source: '夥伴大冒險、釣魚（水深＞５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },
  {
    id: 'ing_021',
    name: '美味尾巴*',
    description: '非常美味的某種尾巴，可作為某些食物的食材。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Ingredient,
  },

  // --- Medicine Category (藥材類) ---
  {
    id: 'med_001',
    name: '療草',
    description: '能用來調合成藥品。生長在洗翠地區各地，被以太基金會釣魚分部研究並擴大養殖，也被稱為旅人良伴。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Medicine,
  },
  {
    id: 'med_002',
    name: '活力蕾',
    description: '也被稱為朝露之花苞。可作為幫瀕死的寶可夢注入活力的道具的材料。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Medicine,
  },
  {
    id: 'med_003',
    name: '皇葉',
    description: '閃耀著光輝的香草之王。與藥物的材料配合，可以提高其回復效果。',
    source: '夥伴大冒險、釣魚（水深＞５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.Medicine,
  },
  {
    id: 'med_004',
    name: '劍舞菇',
    description: '食用後會讓肌肉膨脹，發揮更強力量的菇類。可作為???的材料。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Medicine,
  },
  {
    id: 'med_005',
    name: '鐵壁木耳',
    description: '食用後會讓身體變得堅硬，發揮更強耐力的菇類。可作為???的材料。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Medicine,
  },
  {
    id: 'med_006',
    name: '要害松露',
    description: '食用後會讓注意力更加集中，增加擊中要害機率的菇類。可作為???的材料。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Medicine,
  },
  {
    id: 'med_007',
    name: '甜松露',
    description: '充滿了不可思議能量的甘甜菇類。可作為各種道具的材料。',
    source: '夥伴大冒險、釣魚（水深＞５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.Medicine,
  },
  {
    id: 'med_008',
    name: '永恆之花',
    description: '這株不祥的花朵被認為蘊藏著恐怖的力量，現在在任何地方都沒有開放，但傳聞在某個在隕石坑的城市中有目擊的情報。',
    source: '夥伴大冒險、派遣工作',
    type: ItemType.Material,
    category: ItemCategory.Medicine,
  },
  {
    id: 'med_009',
    name: '精通種子*',
    description: '稀有的種子。將它作為素材能夠製作與夥伴技能有關的道具',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Medicine,
  },

  // --- Other Category (其他類) ---
  {
    id: 'oth_001',
    name: '木材',
    description: '從釣竿到裝飾品，能在製作各種物品時作為材料的好用木材。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Other,
  },
  {
    id: 'oth_002',
    name: '彈子萁',
    description: '能作為道具的材料使用的蕨類植物。將捲成漩渦狀的葉片展開後，就是一張天然的包裝紙。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Other,
  },
  {
    id: 'oth_003',
    name: '電池',
    description: '就只是一個普通的電池。可作為需要電力的道具的素材',
    source: '夥伴大冒險、釣魚（水深＞５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.Other,
  },
  {
    id: 'oth_004',
    name: '常見石',
    description: '在某些人眼裡可能會覺得它十分貴重。但其實是塊普通的石頭。可作為製作釣具的道具的素材',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Other,
  },
  {
    id: 'oth_005',
    name: '黑奇石',
    description: '破碎後會變得十分鋒利，性質類似玻璃的黑石。可作為某些釣具的素材。',
    source: '夥伴大冒險、釣魚（水深＞５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.Other,
  },
  {
    id: 'oth_006',
    name: '絲線',
    description: '在陰濕森林常見的纖維絲，據說有些蟲系寶可夢的身上也能找到，可作為某些釣具的素材。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Other,
  },
  {
    id: 'oth_007',
    name: '銅線',
    description: '海底深處到處可見的遺棄物。曬乾後仍可繼續使用，可作為某些釣具的素材。',
    source: '夥伴大冒險、釣魚（水深＞５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.Other,
  },
  {
    id: 'oth_008',
    name: '彈簧',
    description: '細小的彈簧。已經完全鬆掉，但仍可作為某些釣具的素材。',
    source: '釣魚（水深＞５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.Other,
  },
  {
    id: 'oth_009',
    name: '螺絲',
    description: '海底深處到處可見的遺棄物。主要用於固定機械部件，可作為某些釣具的素材。',
    source: '夥伴大冒險、釣魚（水深＞５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.Other,
  },
  {
    id: 'oth_10',
    name: '機械零件',
    description: '似乎是被人從發電廠裡偷走的重要零件。可作為某些釣具的素材。',
    source: '釣魚（水深＞１５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.Other,
  },
  {
    id: 'oth_011',
    name: '探測器',
    description: '在深海處中找到的道具，看起來是探測水中生物的機器。但似乎很難使用。',
    source: '釣魚（水深＞１５０ｍ）',
    type: ItemType.Material,
    category: ItemCategory.Other,
  },
  {
    id: 'oth_012',
    name: '似珍石',
    description: '在某些人眼裡可能會覺得它十分貴重。頗與眾不同的石頭。',
    source: '？？？',
    type: ItemType.Material,
    category: ItemCategory.Other,
  },
  {
    id: 'oth_013',
    name: '謎之碎片*',
    description: '能感受到神奇力量的小碎片。碎片中浮現著某種花紋。',
    source: '夥伴大冒險、釣魚',
    type: ItemType.Material,
    category: ItemCategory.Other,
  },

  // --- Consumables (消耗品) ---
  {
    id: 'cons_001',
    name: 'SP塊(小)',
    description: '充滿SP的糖果，使用後獲得少量的SP。',
    source: '普通釣竿、感謝釣竿',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_002',
    name: 'SP塊(中)',
    description: '充滿SP的糖果，使用後獲得不少的SP。',
    source: '好釣竿、感謝釣竿',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_003',
    name: 'SP塊(大)',
    description: '充滿SP的糖果，使用後獲得許多的SP。',
    source: '厲害釣竿、感謝釣竿',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_004',
    name: 'SP塊(超大)',
    description: '充滿SP的糖果，使用後獲得大量的SP。',
    source: '???',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_005',
    name: '球匠的遺失物',
    description: '某球匠遺失的物品，裡面似乎存放著製作各類球的素材。',
    source: '普通釣竿、好釣竿、厲害釣竿、感謝釣竿',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_006',
    name: '樹果名人的遺失物',
    description: '某樹果名人遺失的物品，裡面似乎存放著製作各類食物的素材。',
    source: '普通釣竿、好釣竿、厲害釣竿、感謝釣竿',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_007',
    name: '藥材袋',
    description: '某少女藥師遺失的物品，裡面似乎存放著製作各類藥品的素材。',
    source: '好釣竿、厲害釣竿、感謝釣竿',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_008',
    name: '瑪奧的材料袋',
    description: '瑪奧用於放入收集到的食材的袋子，裡面似乎存放著製作特定食物用的素材。',
    source: '厲害釣竿、感謝釣竿',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_009',
    name: '大吾的收藏品',
    description: '裡面放有大吾四處旅行時收集到的各式各樣的石頭。',
    source: '???',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_010',
    name: '關都球',
    description: '一顆捕獲了關都寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_011',
    name: '城都球',
    description: '一顆捕獲了來自城都的寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_012',
    name: '豐緣球',
    description: '一顆捕獲了來自豐緣的寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_013',
    name: '神奧球',
    description: '一顆捕獲了來自神奧的寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_014',
    name: '合眾球',
    description: '一顆捕獲了來自合眾的寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_015',
    name: '卡洛斯球',
    description: '一顆捕獲了來自卡洛斯的寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_016',
    name: '阿羅拉球',
    description: '一顆捕獲了來自阿羅拉的寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_017',
    name: '伽勒爾球',
    description: '一顆捕獲了來自伽勒爾的寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_018',
    name: '帕底亞球',
    description: '一顆捕獲了來自帕底亞的寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_019',
    name: 'GS球',
    description: '刻有「世代共感」字樣的神秘精靈球，似乎捕獲了來自各個世代的寶可夢，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_020',
    name: '普通釣竿使用券',
    description: '使用後能免費用一次普通釣竿。',
    source: '商店、合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_021',
    name: '好釣竿使用券',
    description: '使用後能免費用一次好釣竿。',
    source: '商店、合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_022',
    name: '厲害釣竿使用券',
    description: '使用後能免費用一次厲害釣竿。',
    source: '商店、合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_023',
    name: '認真薄荷',
    description: '對隊伍首位的夥伴使用，將其性格變為「認真」，會令攻擊、防禦、速度和耐力均衡地成長。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_024',
    name: '勤奮薄荷',
    description: '對隊伍首位的夥伴使用，將其性格變為「勤奮」，道具掉落率提升10%，耐力下降10%。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_025',
    name: '坦率薄荷',
    description: '對隊伍首位的夥伴使用，將其性格變為「坦率」，獲得經驗值提升10%，耐力下降10%。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_026',
    name: '害羞薄荷',
    description: '對隊伍首位的夥伴使用，將其性格變為「害羞」，耐力提升10%，獲得經驗值下降10%。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_027',
    name: '浮躁薄荷',
    description: '對隊伍首位的夥伴使用，將其性格變為「浮躁」，耐力提升10%，道具掉落率下降10%。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_028',
    name: '怕寂寞薄荷',
    description: '對隊伍首位的夥伴使用，將其性格變為「怕寂寞」，攻擊提升10%，防禦下降10%。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_029',
    name: '勇敢薄荷',
    description: '對隊伍首位的夥伴使用，將其性格變為「勇敢」，攻擊提升10%，速度下降10%。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_030',
    name: '大膽薄荷',
    description: '對隊伍首位的夥伴使用，將其性格變為「大膽」，防禦提升10%，攻擊下降10%。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_031',
    name: '悠閒薄荷',
    description: '對隊伍首位的夥伴使用，將其性格變為「悠閒」，防禦提升10%，速度下降10%。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_032',
    name: '膽小薄荷',
    description: '對隊伍首位的夥伴使用，將其性格變為「膽小」，速度提升10%，攻擊下降10%。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_033',
    name: '急躁薄荷',
    description: '對隊伍首位的夥伴使用，將其性格變為「急躁」，速度提升10%，防禦下降10%。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_034',
    name: '經驗糖果(小)',
    description: '充滿能量的糖果。餵給夥伴後，能讓增加少量經驗值。',
    source: '普通釣竿、感謝釣竿',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_035',
    name: '經驗糖果(中)',
    description: '充滿能量的糖果。餵給夥伴後，能讓增加經驗值。',
    source: '好釣竿、感謝釣竿',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_036',
    name: '經驗糖果(大)',
    description: '充滿能量的糖果。餵給夥伴後，能讓增加許多經驗值。',
    source: '厲害釣竿、感謝釣竿',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_037',
    name: '經驗糖果(超大)',
    description: '充滿能量的糖果。餵給夥伴後，能讓增加大量經驗值。',
    source: '???',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_038',
    name: '心形甜點',
    description: '對隊伍首位的夥伴使用，提高８０點親密度。',
    source: '???',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_039',
    name: '小小花束',
    description: '竭盡心力製作的花束。雖然不起眼，但裡頭充滿了對訓練家的心意。 對隊伍首位的夥伴使用，提高２０點親密度。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_040',
    name: '奧多馬雷特產',
    description: '對隊伍首位的夥伴使用，能夠提升主技能的基礎等級。',
    source: '???',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_041',
    name: '主技能光碟',
    description: '對隊伍首位的夥伴使用，能夠根據光碟中的內容改變夥伴的主技能。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_042',
    name: '傷藥',
    description: '噴霧式傷藥。能讓１隻寶可夢回復３０ＨＰ。',
    source: '合成、普通釣竿、感謝釣竿',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_043',
    name: '好傷藥',
    description: '噴霧式傷藥。能讓１隻寶可夢回復８０ＨＰ。',
    source: '合成、好釣竿、感謝釣竿',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_044',
    name: '厲害傷藥',
    description: '噴霧式傷藥。能讓１隻寶可夢回復１５０ＨＰ。',
    source: '合成、厲害釣竿、感謝釣竿',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_045',
    name: '全復藥',
    description: '能回復１隻寶可夢的所有ＨＰ。',
    source: '訂閱包裹',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_046',
    name: '樹果汁',
    description: '１００％樹果果汁。能讓１隻寶可夢回復２０ＨＰ',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_047',
    name: '技能膠囊',
    description: '對隊伍首位的夥伴使用，能夠隨機更改其中一個擁有的副技能。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_048',
    name: '升級資料',
    description: '對隊伍首位的夥伴使用，能夠升級其中一個擁有的副技能階級，西爾佛公司製造。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_049',
    name: '可疑修正檔',
    description: '內部儲存了可疑資訊的透明機器。製造者不明。 對隊伍首位的夥伴使用，能夠改變目前的主技能',
    source: '???',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_050',
    name: '捕網球',
    description: '一顆捕獲了蟲系寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_051',
    name: '火炎球',
    description: '一顆捕獲了火系寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_052',
    name: '誘餌球',
    description: '一顆捕獲了水系寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_053',
    name: '大地球',
    description: '一顆捕獲了地面系寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_054',
    name: '夢境球',
    description: '一顆捕獲了超能力系寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_055',
    name: '沉重球',
    description: '一顆捕獲了鋼系寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_056',
    name: '冰晶球',
    description: '一顆捕獲了冰系寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_057',
    name: '飛羽球',
    description: '一顆捕獲了飛行系寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_058',
    name: '靈魂球',
    description: '一顆捕獲了幽靈系寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '合成',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_059',
    name: '奇異球',
    description: '一顆來自各個可能性的精靈球，心中默念的寶可夢能夠在打開時加入自己的隊伍裡。',
    source: '里程獎勵',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_060',
    name: '貴重球',
    description: '一顆捕獲了幻之寶可夢的精靈球，打開能夠使其加入自己的隊伍裡。',
    source: '里程獎勵',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_061',
    name: '球果汁',
    description: '一杯味道均衡且充滿驚喜的果汁。 對隊伍首位的夥伴使用，能夠平均的改變夥伴的所有體能',
    source: '古代遺物交換所',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_062',
    name: '力量果汁',
    description: '一杯味道強烈且後勁滿滿的果汁。 對隊伍首位的夥伴使用，能夠注重於改變夥伴的力量體能',
    source: '古代遺物交換所',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_063',
    name: '耐力果汁',
    description: '一杯味道乾澀且十分健康的果汁。 對隊伍首位的夥伴使用，能夠注重於改變夥伴的耐力體能',
    source: '古代遺物交換所',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_064',
    name: '技巧果汁',
    description: '一杯味道有趣且挑戰性滿滿的果汁。 對隊伍首位的夥伴使用，能夠注重於改變夥伴的技巧體能',
    source: '古代遺物交換所',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_065',
    name: '速度果汁',
    description: '一杯味道刺激且嗆鼻的果汁。 對隊伍首位的夥伴使用，能夠注重於改變夥伴的速度體能',
    source: '古代遺物交換所',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_066',
    name: '奮鬥沙',
    description: '不可思議的沙子。能讓寶可夢的奮鬥等級提升。可用於奮鬥等級０～２的寶可夢。',
    source: '合成、Boss挑戰',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_067',
    name: '奮鬥礫',
    description: '不可思議的沙礫。能讓寶可夢的奮鬥等級提升。可用於奮鬥等級３～５的寶可夢。',
    source: '合成、Boss挑戰',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_068',
    name: '奮鬥石',
    description: '不可思議的石塊。能讓寶可夢的奮鬥等級提升。可用於奮鬥等級６～８的寶可夢。',
    source: '合成、Boss挑戰',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  {
    id: 'cons_069',
    name: '奮鬥岩',
    description: '不可思議的岩石。能讓寶可夢的奮鬥等級提升。可用於奮鬥等級９的寶可夢。',
    source: '合成、Boss挑戰',
    type: ItemType.Consumable,
    category: ItemCategory.None,
  },
  // --- Held Items (攜帶物) ---
  {
    id: 'held_001',
    name: '護符金幣',
    description: '只要攜帶它的夥伴在釣魚時在隊伍首位，獲得的SP就會變為１.５倍。',
    source: '夥伴大冒險（啟程草原）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_002',
    name: '幸運蛋',
    description: '攜帶的夥伴能得到稍微更多的經驗值。',
    source: '夥伴大冒險（啟程草原）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_003',
    name: '吃剩的東西',
    description: '攜帶後，在戰鬥結束時體力會回復少許ＨＰ',
    source: '夥伴大冒險（啟程草原）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_004',
    name: '光粉',
    description: '攜帶後，光芒會產生迷惑，戰鬥時對手的命中率會降低。',
    source: '夥伴大冒險（陰濕森林）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_005',
    name: '潔淨之符',
    description: '攜帶後，進行夥伴大冒險時較不容易遭遇到戰鬥。',
    source: '夥伴大冒險（陰濕森林）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_006',
    name: '玉蟲石板',
    description: '蟲屬性的石板。攜帶後，蟲屬性夥伴戰鬥時造成的傷害就會增強。',
    source: '夥伴大冒險（陰濕森林）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_007',
    name: '氣勢頭帶',
    description: '攜帶後，受到導致瀕死的傷害能有一次的機會能以１ＨＰ撐過去。',
    source: '夥伴大冒險（渡假沙灘）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_008',
    name: '凸凸頭盔',
    description: '攜帶後，在受到打擊招式攻擊時，也能給予對手傷害。',
    source: '夥伴大冒險（渡假沙灘）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_009',
    name: '水滴石板',
    description: '水屬性的石板。攜帶後，水屬性夥伴戰鬥時造成的傷害就會增強。',
    source: '夥伴大冒險（渡假沙灘）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_010',
    name: '火球石板',
    description: '火屬性的石板。攜帶後，火屬性夥伴戰鬥時造成的傷害就會增強。',
    source: '夥伴大冒險（劍山原野）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_011',
    name: '萬能傘',
    description: '攜帶它的夥伴將不會受任何場地效果所影響。',
    source: '夥伴大冒險（劍山原野）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_012',
    name: '安撫之鈴',
    description: '音色悅耳的鈴鐺。攜帶它的夥伴的心情會平靜下來，變得更容易親近人。',
    source: '夥伴大冒險（劍山原野）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_013',
    name: '破壞基因',
    description: '某位科學家長年累月持續進行可怕的遺傳基因研究實驗所誕生的物質。 攜帶的夥伴在戰鬥開始時攻擊強化２階，但攻擊有機會失敗。',
    source: '活動期間取得（奇幻島嶼現身！？）、商店',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_014',
    name: '靛藍色寶珠',
    description: '據說和豐緣地區的傳說有著很深淵源的，散發著藍色光輝的寶珠。 攜帶後，如果場地在下雨，在回合結束時會根據最大體力回復少許ＨＰ 讓釣魚夥伴「蓋歐卡」攜帶的話，進入戰鬥時能夠使其「原始回歸」',
    source: '夥伴大冒險（渡假沙灘）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_015',
    name: '朱紅色寶珠',
    description: '據說和豐緣地區的傳說有著很深淵源的，散發著紅色光輝的寶珠。 攜帶後，如果場地在大晴天，在回合結束時會根據最大體力回復少許ＨＰ 讓釣魚夥伴「固拉多」攜帶的話，進入戰鬥時能夠使其「原始回歸」',
    source: '？？？',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_016',
    name: '神奇石板',
    description: '超能屬性的石板。攜帶後，超能屬性夥伴戰鬥時造成的傷害就會增強。',
    source: '活動期間取得（奧多馬雷）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_017',
    name: '清淨墜飾',
    description: '澄澈晶瑩的墜飾。攜帶後，不會因對手的技能而被降低能力。',
    source: '活動期間取得（奧多馬雷）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_018',
    name: '心之水滴',
    description: '散發著美麗光輝的寶珠。超能力系的夥伴攜帶後，攻擊和防禦就會提高。 讓釣魚夥伴「拉帝歐斯」或「拉帝亞斯」攜帶後，進入戰鬥時能夠使其「超級進化」',
    source: '活動期間取得（奧多馬雷）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_019',
    name: '不融冰',
    description: '隔絕熱的冰。攜帶後，冰屬性夥伴戰鬥時的防禦力會增強。',
    source: '？？？',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_020',
    name: '銳利鳥嘴',
    description: '又長又尖的鳥嘴。攜帶後，飛行性夥伴戰鬥時造成的傷害就會增強。',
    source: '？？？',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_021',
    name: '吉利拳',
    description: '能帶來幸運的拳套。讓夥伴攜帶後，戰鬥時變得有點容易擊中要害。 如果讓釣魚夥伴「吉利蛋」攜帶後，會變得非常容易擊中要害。',
    source: '夥伴大冒險（啟程草原EX）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_022',
    name: '學習裝置',
    description: '攜帶後能夠將經驗值分享給另外兩個沒有參與戰鬥的釣魚夥伴',
    source: '合成',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_023',
    name: '焦點鏡',
    description: '能看見弱點的鏡片。攜帶它的夥伴戰鬥時會變得容易擊中要害。',
    source: '合成',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_024',
    name: '飽腹薰香',
    description: '有著神奇香氣的薰香。攜帶後，能夠比較容易釣到食物系列的花紋',
    source: '合成',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_025',
    name: '硬石頭',
    description: '絕對不會裂開的石頭。攜帶後，岩石屬性夥伴戰鬥時的防禦力會增強。',
    source: '？？？',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_026',
    name: '金屬膜',
    description: '特殊的金屬膜。攜帶後，鋼屬性夥伴戰鬥時的防禦力會增強。',
    source: '？？？',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_027',
    name: '妖怪石板',
    description: '幽靈屬性的石板。攜帶後，幽靈屬性夥伴戰鬥時造成的傷害就會增強。',
    source: '活動期間取得（森之洋館）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_028',
    name: '靈界之布',
    description: '蘊含著驚人的強大靈力的布。攜帶後並戰鬥時， 幽靈屬性夥伴的防禦力會增強、惡屬性夥伴的速度會增強。（可疊加）',
    source: '活動期間取得（森之洋館）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_029',
    name: '白金寶珠',
    description: '散發著光輝的寶珠。攜帶後並戰鬥時， 幽靈屬性夥伴的攻擊力會增強、龍屬性夥伴的防禦力會增強。(可疊加)',
    source: '活動期間取得（森之洋館）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_030',
    name: '銀粉',
    description: '散發著銀色光輝的粉末。攜帶後並戰鬥時， 蟲屬性的夥伴偶爾會給予對手「混亂」的異常狀態。',
    source: '夥伴大冒險（陰濕森林EX）',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  {
    id: 'held_031',
    name: '快龍進化石',
    description: '讓快龍攜帶後，在戰鬥時就能進行超級進化的一種神奇超級石。',
    source: '合成',
    type: ItemType.HeldItem,
    category: ItemCategory.None,
  },
  // --- Key Items (重要) ---
  {
    id: 'key_001',
    name: '外觀券',
    description: '擁有這張卡，就能在商店買到更多商品。',
    source: '訂閱包裹',
    type: ItemType.KeyItem,
    category: ItemCategory.None,
  },
  {
    id: 'key_002',
    name: '古代銅幣',
    description: '距今約３０００年前的文明裡使用的銅幣。 能夠在「古代遺物交換所」兌換各式各樣的東西。',
    source: '野生遭遇、夥伴大冒險',
    type: ItemType.KeyItem,
    category: ItemCategory.None,
  },
  {
    id: 'key_003',
    name: '古代銀幣',
    description: '距今約３０００年前的文明裡使用的銀幣。 能夠在「古代遺物交換所」兌換各式各樣的東西。',
    source: '野生遭遇、夥伴大冒險',
    type: ItemType.KeyItem,
    category: ItemCategory.None,
  },
  {
    id: 'key_004',
    name: '古代金幣',
    description: '距今約３０００年前的文明裡使用的金幣。 能夠在「古代遺物交換所」兌換各式各樣的東西。',
    source: '野生遭遇、夥伴大冒險',
    type: ItemType.KeyItem,
    category: ItemCategory.None,
  },
  {
    id: 'key_005',
    name: '謎之水晶',
    description: '從地下挖出的水晶球。雖然表面覆蓋著岩石和塵土，但非常漂亮。 能夠在「古代遺物交換所」兌換到很稀有的東西。',
    source: '夥伴大冒險',
    type: ItemType.KeyItem,
    category: ItemCategory.None,
  },
  {
    id: 'key_006',
    name: '體能競賽證明',
    description: '參加夥伴體能競賽的證明。上面印有紀念獎章。 能夠在「夥伴體能競技賽巨蛋」兌換到很特別的東西',
    source: '參加「夥伴體能競賽」',
    type: ItemType.KeyItem,
    category: ItemCategory.None,
  },
  {
    id: 'key_007',
    name: '基格爾德・細胞',
    description: '「據說當生態嚴重失衡時會根據核心的指令而匯聚一起， 傳說的秩序守護神將會現身...」',
    source: '特殊夥伴主技能（細胞蒐集者）',
    type: ItemType.KeyItem,
    category: ItemCategory.None,
  },
  {
    id: 'key_008',
    name: '基格爾德・核心(再生)',
    description: '指令代號「再生」，由此核心組成的基格爾德具有自我修復的能力。',
    source: '特殊夥伴主技能（細胞蒐集者）',
    type: ItemType.KeyItem,
    category: ItemCategory.None,
  },
  {
    id: 'key_009',
    name: '基格爾德・核心(死神)',
    description: '指令代號「死神」，由此核心組成的基格爾德具有細胞破壞的能力。 傳聞沒有敵人看到此姿態的基格爾德後能夠存活。',
    source: '特殊夥伴主技能（細胞蒐集者）',
    type: ItemType.KeyItem,
    category: ItemCategory.None,
  },
  {
    id: 'key_010',
    name: '基格爾德・核心(宗師)',
    description: '指令代號「宗師」，由此核心組成的基格爾德具有光束攻擊的能力。 「想阻止我的話...就展現出你的力量吧！」',
    source: '特殊夥伴主技能（細胞蒐集者）',
    type: ItemType.KeyItem,
    category: ItemCategory.None,
  },
  {
    id: 'key_011',
    name: '洛托姆型錄',
    description: '記載著洛托姆喜歡的電器。透過使用這本型錄，可以讓洛托姆進入或離開電器。',
    source: '夥伴大冒險（森之洋樓）',
    type: ItemType.KeyItem,
    category: ItemCategory.None,
  },
  {
    id: 'key_012',
    name: '大海石板',
    description: '充滿神奇力量的石板。感覺它和某地有很深的關係。 有了這個石板就能夠前往「渡假沙灘」進行夥伴大冒險',
    source: '夥伴大冒險（劍山原野）',
    type: ItemType.KeyItem,
    category: ItemCategory.None,
  },
  // --- LunchBox Category (餐盒) ---
  {
    id: 'food_001',
    name: '原味誘糰',
    description: '僅由誘糰原料反覆揉合而成。有著非常單調的口味。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_002',
    name: '酸誘糰',
    description: '由酸酸的果實與誘糰原料揉合而成。對喜愛酸味的夥伴有著很強的吸引力。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_003',
    name: '甜誘糰',
    description: '由甜甜的果實與誘糰原料揉合而成。對喜愛甜味的夥伴有著很強的吸引力。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_004',
    name: '苦誘糰',
    description: '由苦苦的果實與誘糰原料揉合而成。對喜愛苦味的夥伴有著很強的吸引力。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_005',
    name: '辣誘糰',
    description: '由辣辣的果實與誘糰原料揉合而成。對喜愛辣味的夥伴有著很強的吸引力。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_006',
    name: '澀誘糰',
    description: '由澀的果實與誘糰原料揉合而成。對喜愛澀味的夥伴有著很強的吸引力。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_007',
    name: '鹹誘糰',
    description: '由鹹的果實與誘糰原料揉合而成。對喜愛鹹味的夥伴有著很強的吸引力。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_008',
    name: '鮮誘糰',
    description: '由鮮的果實與誘糰原料揉合而成。對喜愛鮮味的夥伴有著很強的吸引力。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_009',
    name: '大馬拉薩達',
    description: '阿羅拉特產的油炸麵包。即便是原味也能夠給予無比的幸福。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_010',
    name: '深灰米果',
    description: '深灰市特產的米果。清脆的口感深受聖特安努號乘客們的喜愛。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_011',
    name: '森之羊羹',
    description: '百代不為人知的特產。口中化開的甜味中和了天然的澀味，喜愛豆類的夥伴對此愛不釋手。順帶一提，字面上和森之洋館沒有關聯。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_012',
    name: '濃縮甜蜜',
    description: '由罕見的特殊蜂女王製造的蜜汁的複製品。放進湯裡，湯就會變得又甜又醇。即便是仿製品，傳聞仍有與活力塊相同的效果',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_013',
    name: '裡脊岩',
    description: '自遙遠的大陸傳過來的食物。雖然是肉的形狀，但外部卻堅不可摧，似乎只有喜愛礦類的夥伴知道其真正的味道為何。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_014',
    name: '芳香蘑菇',
    description: '能讓附近一帶充滿馥郁香氣的稀奇蘑菇。既可在商店高價出售，也能夠當作喜愛菇類的夥伴之間的上等食物。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_015',
    name: '奶油起司',
    description: '帶有甜味、酸味和鹹味的調味料。能搭配的食材意外地多，是很好使用的百搭食材。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_016',
    name: '三明治',
    description: '用麵包夾著蔬菜、肉類等材料而成。作為野餐料理再適合不過。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_017',
    name: '魚奶油湯',
    description: '一道加入切碎魚肉的牛奶湯，濃郁的高湯賦予它獨特的風味。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_018',
    name: '美味米飯',
    description: '煮熟的米飯搭配美味的尾巴。就算沒特別經過調味也相當美味。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  },
  {
    id: 'food_019',
    name: '煙燻尾巴',
    description: '在伽勒爾地區製作露營料理時使用的食材之一。寶可夢呆呆獸的尾巴，就算掉了也會馬上長回來。經過煙燻處理後非常美味。',
    source: '合成',
    type: ItemType.LunchBox,
    category: ItemCategory.None,
  }
];
