import { Fish, Rarity } from './types';

export const INITIAL_FISH: Fish[] = [
  {
    id: '001',
    name: '大眼草魚',
    description: '有著不成比例大眼睛的淡水魚，常在水草間發呆。',
    rarity: Rarity.OneStar,
    location: '新手村池塘',
    time: '全天',
    weather: '晴天/陰天',
    battleRequirements: '點擊頻率：低',
    tags: ['新手區', '淡水'],
  },
  {
    id: '002',
    name: '泥沼鯰',
    description: '身體滑溜溜的，喜歡躲在淤泥裡，拉力比想像中大。',
    rarity: Rarity.OneStar,
    location: '沼澤邊緣',
    time: '夜間',
    weather: '雨天',
    battleRequirements: '維持張力在黃色區域',
    tags: ['沼澤', '夜行性'],
  },
  {
    id: '010',
    name: '翠玉鱸魚',
    description: '鱗片像寶石一樣閃爍著綠光的鱸魚，肉質鮮美。',
    rarity: Rarity.TwoStar,
    location: '翡翠溪谷',
    time: '清晨 (05:00 - 08:00)',
    weather: '晴天',
    battleRequirements: '需要快速反應QTE',
    tags: ['溪流', '寶石系列'],
  },
  {
    id: '015',
    name: '雷紋鰻',
    description: '背部有黃色閃電花紋，生氣時會放出微弱電流。',
    rarity: Rarity.TwoStar,
    location: '雷鳴斷崖下',
    time: '雷雨天',
    weather: '雷雨',
    battleRequirements: '避免在牠放電(紅光)時拉線',
    tags: ['雷屬性', '危險生物'],
  },
  {
    id: '030',
    name: '深淵燈籠魚',
    description: '生活在極深水域，頭上的燈籠會迷惑釣客。',
    rarity: Rarity.ThreeStar,
    location: '無底湖中心',
    time: '深夜 (22:00 - 04:00)',
    weather: '霧天',
    battleRequirements: '張力條會忽快忽慢，需要極高專注',
    tags: ['深海', '發光生物'],
  },
  {
    id: '035',
    name: '赤炎鬥魚',
    description: '全身燃燒著像是火焰的靈氣，水溫會因為牠而升高。',
    rarity: Rarity.ThreeStar,
    location: '火山熱泉',
    time: '正午 (11:00 - 13:00)',
    weather: '酷熱',
    battleRequirements: '連續點擊破壞護盾',
    tags: ['火屬性', '火山'],
  },
  {
    id: '050',
    name: '月光女神',
    description: '傳說中映照著月亮的幻之魚，鰭如絲綢般飄逸。',
    rarity: Rarity.FourStar,
    location: '星落湖',
    time: '滿月之夜',
    weather: '晴朗無雲',
    battleRequirements: '完美判定連擊 x10',
    tags: ['傳說', '夢幻'],
  },
  {
    id: '051',
    name: '遠古利維坦幼體',
    description: '雖然只是幼體，但已有吞噬小船的怪力，來自遠古的霸主。',
    rarity: Rarity.FourStar,
    location: '深海海溝',
    time: '暴風雨',
    weather: '暴風雨',
    battleRequirements: '需裝備鈦合金釣竿，耐力戰 5 分鐘',
    tags: ['傳說', '巨獸', '深海'],
  },
  {
    id: '999',
    name: '錯誤代碼：404',
    description: '一隻由雜訊構成的魚，存在於現實與數據的夾縫中。',
    rarity: Rarity.Special,
    location: '虛空裂縫',
    time: '伺服器維護前',
    weather: '電磁風暴',
    // No battle requirements provided for this one to test optional field
    tags: ['異變', '數位'],
  },
];